;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-change
        evil-forward-word-begin
        evil-next-line
        evil-normal-state
        evil-previous-line
        ))

(setq mc/cmds-to-run-once
      '(
        ccm-mwheel-scroll
        evil-delete-backward-char-and-join
        evil-mouse-drag-region
        evil-search-previous
        evil-visual-char
        org-self-insert-command
        ))
