#!/bin/sh


# set the monitors layout
# xrandr --output DVI-I-0 --off --output DVI-I-1 --mode 1280x1024 --pos 0x56 --rotate normal --output DVI-I-2 --primary --mode 1920x1080 --pos 1280x0 --rotate normal --output HDMI-0 --off --output DVI-I-3 --off

# second monitor on the left
# xrandr --output DVI-I-0 --off --output DVI-I-1 --mode 1280x1024 --pos 0x56 --rotate normal --output DVI-I-2 --primary --mode 1920x1080 --pos 1280x0 --rotate normal --output HDMI-0 --off --output DVI-I-3 --off

# second monitor on the right
xrandr --output DVI-I-0 --off --output DVI-I-1 --mode 1280x1024 --pos 1920x56 --rotate normal --output DVI-I-2 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-0 --off --output DVI-I-3 --off


# xrandr --output DVI-I-2 --primary --right-of DVI-I-1
# xrandr --output DVI-I-1 --left-of DVI-I-2 --primary

# after last format xrandr inverted the names of monitors, dunno why
bspc monitor DVI-I-2 -d 1 2 3 4 5 6 7
bspc monitor DVI-I-1 -d 8 9 10

# maybe this is only needed when the second monitor is on the left. testing it
# bspc monitor DVI-I-1 -s DVI-I-2

# start key manager
[[ ! $(pidof -x sxhkd) ]] && sxhkd &

# run function to check for existing instances and avoid duplicates
function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}

# change the mouse cursor to left pointer
xsetroot -cursor_name left_ptr &

# change repeat rate of keyboard
xset r rate 250 70 &

#change your keyboard if you need it
setxkbmap -layout br &

# swap caps for esc
setxkbmap -option caps:swapescape &
# xmodmap ~/.Xmodmap &


# launch polybar
# [[ ! $(pidof -x polybar) ]] && $HOME/.config/polybar/launch.sh &
$HOME/.config/polybar/launch.sh &

[[ ! $(pidof -x picom) ]] && picom &

# sound
pulseaudio --start

# applets and utilities
run numlockx on &
run nm-applet &
run volumeicon &


#################################################################
# WALLPAPER, LOCKSCREEN AND SCREENSAVER
#################################################################

# set the Energy Star feature to On and sets it to wait 10 minutes of inactivity to turn off the screens.
xset dpms 600 &

# wallpaper setup
nitrogen --restore &

# wal --theme base16-eighties
# restore last pywall colorscheme
wal -R


# Run ./pacwall.sh -W to use colors set by pywal.
# pacwall -W

# pscircle \
#   --output-width=1890 \
#   --output-height=980 \

# Set random lockscreen image
betterlockscreen -u ~/wallpapers &

# Auto lockscreen with betterlockscreen using dim and blur effects and turning screen off after 600 seconds
xautolock -time 5 -locker "betterlockscreen -u ~/wallpapers --lock dimblur --off 600" &


#################################################################
# BSPWM configuration
#################################################################

#bspc config border_radius       8
bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
# bspc config remove_disabled_monitors true
# bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#dd2727"


#################################################################
# Fullscreen applications
#################################################################

bspc rule -a inkscape state=fullscreen
bspc rule -a Spotify state=fullscreen
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen
#bspc rule -a Gimp state=fullscreen

#################################################################
# Floating applications
#################################################################

bspc rule -a Arandr state=floating
bspc rule -a Lutris state=floating
bspc rule -a Diablo state=floating
bspc rule -a feh state=floating
#bspc rule -a mpv state=floating sticky=on
bspc rule -a Font-manager state=floating
#bspc rule -a Gpick state=floating sticky=on
bspc rule -a Nitrogen state=floating center=true
bspc rule -a Oblogout state=floating
bspc rule -a Pavucontrol state=floating sticky=on
bspc rule -a Peek state=floating
bspc rule -a rofi state=floating sticky=on
#bspc rule -a Skype state=floating

# wine games (rules applied using instances instead of class)
bspc rule -a wine state=floating
bspc rule -a Wine:diablo.exe state=floating
bspc rule -a Wine:Diablo_Copy.exe state=floating
#################################################################
# Tiled applications
#################################################################

bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
bspc rule -a Emacs state=tiled

#################################################################
# Open applications on specific workspaces
#################################################################

bspc rule -a Firefox desktop='^3' follow=on
bspc rule -a Google-chrome desktop='^3' follow=on
#bspc rule -a Chromium desktop='^1'  follow=on
#bspc rule -a Subl3 desktop='^2' follow=on
#bspc rule -a Atom desktop='^2' follow=on
bspc rule -a Steam desktop='^5'
#bspc rule -a vlc desktop='^6'  follow=on
#bspc rule -a mpv desktop='^6'  follow=on
#bspc rule -a Vivaldi-stable desktop='^6' follow=on
#bspc rule -a Vivaldi-snapshot desktop='^6' follow=on
bspc rule -a Transmission-gtk desktop='^7' follow=on
#bspc rule -a Thunar desktop='^8' follow=on
bspc rule -a discord desktop='^10' follow=on
#bspc rule -a Spotify desktop='^10' follow=on

#Spotify fix  --move desktop 10
#sleep 1
#wmctrl -r Spotify -t 10
#exit

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)


#################################################################
# SCRATCHPADS
#################################################################

term=st
# alacritty class flag
# term_wm_set_prop_flag=--class
# st class flag
term_wm_set_prop_flag=-c
term_wm_prop=instance

# st
# term_wm_set_prop_flag=-c
# term_wm_prop=instance

# uxrvt
# term_wm_set_prop_flag=-T
# term_wm_prop=title

# terminal scratchpad
bspc rule -a terminal-scratchpad sticky=on state=floating hidden=on rectangle=900x700+0+0 center=true
 [[ ! $(xdotool search --class terminal-scratchpad)  ]] &&  $term $term_wm_set_prop_flag terminal-scratchpad &
# alacritty --class dropdown -e "zsh -i" &

# ranger scratchpad
bspc rule -a ranger-scratchpad sticky=on state=floating hidden=on rectangle=1200x900+0+0 center=true
[[ ! $(xdotool search --class ranger-scratchpad)  ]] && $term $term_wm_set_prop_flag ranger-scratchpad -e 'ranger' &


# galculator scratchpad
bspc rule -a Galculator sticky=on state=floating hidden=on center=true
[[ ! $(pidof -x galculator) ]] && galculator &


# Welcome message
# this also helps me to check if bspwm got to the end of the config file
dunstify "Bem Vindo ${USER^}!" &
