#! /bin/sh

sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor DVI-I-1 -d 7 8 9 10
bspc monitor DVI-I-2 -d 1 2 3 4 5 6

# xrandr --output DVI-I-2 --primary --right-of DVI-I-1

bspc config border_width         2
bspc config window_gap          12

# [[ ! $(pidof -x polybar) ]] && $HOME/.config/polybar/launch.sh &

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
