(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(aggressive-indent-comments-too t)
 '(company-auto-complete (quote company-explicit-action-p))
 '(company-begin-commands (quote (self-insert-command)))
 '(company-box-backends-colors nil t)
 '(company-box-doc-delay 0.3)
 '(company-box-max-candidates 50)
 '(company-box-show-single-candidate t)
 '(company-complete-number t t)
 '(company-dabbrev-code-everywhere t)
 '(company-dabbrev-code-other-buffers t)
 '(company-dabbrev-downcase nil)
 '(company-dabbrev-ignore-case t)
 '(company-dabbrev-other-buffers t)
 '(company-echo-delay 0 t)
 '(company-idle-delay 0.1)
 '(company-lsp-cache-candidates (quote auto) t)
 '(company-minimum-prefix-length 1)
 '(company-require-match nil)
 '(company-selection-wrap-around t)
 '(company-show-numbers t)
 '(company-tooltip-align-annotations t)
 '(company-tooltip-limit 20)
 '(company-transformers (quote (company-sort-by-occurrence)))
 '(counsel-ag-base-command "ag -S --nocolor --nogroup %s")
 '(counsel-describe-function-function (quote helpful-callable))
 '(counsel-describe-variable-function (quote helpful-variable))
 '(counsel-find-file-at-point t)
 '(counsel-find-file-ignore-regexp "\\(?:^[#.]\\)\\|\\(?:[#~]$\\)\\|\\(?:^Icon?\\)")
 '(counsel-grep-base-command
   "ag -S --noheading --nocolor --nofilename --numbers '%s' %s")
 '(counsel-pt-base-command "pt -S --nocolor --nogroup -e %s")
 '(counsel-rg-base-command "rg -S --no-heading --line-number --color never %s .")
 '(counsel-yank-pop-height 15 t)
 '(enable-recursive-minibuffers t)
 '(evil-default-cursor t)
 '(evil-emacs-state-cursor (quote ("#ff0000" box)) t)
 '(evil-esc-delay 0)
 '(evil-ex-complete-emacs-commands nil)
 '(evil-goggles-duration 0.2 t)
 '(evil-goggles-enable-change t t)
 '(evil-goggles-enable-commentary t t)
 '(evil-goggles-enable-delete t t)
 '(evil-goggles-enable-indent t t)
 '(evil-goggles-enable-paste t t)
 '(evil-goggles-enable-redo t t)
 '(evil-goggles-enable-set-marker t t)
 '(evil-goggles-enable-surround t t)
 '(evil-goggles-enable-undo t t)
 '(evil-goggles-enable-yank t t)
 '(evil-goggles-pulse t t)
 '(evil-insert-state-cursor (quote ("#e2f00f" bar)) t)
 '(evil-magic (quote very-magic))
 '(evil-mode-line-format (quote (before . mode-line-front-space)))
 '(evil-motion-state-cursor (quote ("#FFFFFF" box)) t)
 '(evil-normal-state-cursor (quote ("#00ff00" box)) t)
 '(evil-operator-state-cursor (quote ("red" hollow)) t)
 '(evil-regexp-search t)
 '(evil-replace-state-cursor (quote ("red" hbar)) t)
 '(evil-search-module (quote isearch-regexp))
 '(evil-search-wrap t)
 '(evil-shift-round nil)
 '(evil-shift-width 2)
 '(evil-split-window-below t)
 '(evil-visual-state-cursor (quote ("#abcdef" box)) t)
 '(evil-vsplit-window-right t)
 '(evil-want-C-u-scroll t)
 '(evil-want-abbrev-expand-on-insert-exit nil)
 '(evil-want-fine-undo nil)
 '(evil-want-integration nil)
 '(flycheck-check-syntax-automatically (quote (save mode-enabled newline)))
 '(flycheck-display-errors-delay 1)
 '(flycheck-idle-change-delay 1.5)
 '(flycheck-indication-mode (quote left-fringe))
 '(hydra-posframe-parameters (quote ((left-fringe . 5) (right-fringe . 5))))
 '(ivy-display-style (quote fancy))
 '(ivy-on-del-error-function nil)
 '(ivy-re-builders-alist (quote ((t . ivy-prescient-re-builder))) t)
 '(ivy-use-selectable-prompt t)
 '(ivy-use-virtual-buffers t)
 '(lsp-prefer-flymake nil)
 '(package-selected-packages
   (quote
    (ws-butler better-jumper zoom zones zone-nyan yasnippet-snippets xref-js2 xkcd which-key web-server web-mode-edit-element web-beautify vscode-icon volatile-highlights vimrc-mode vi-tilde-fringe vc-msg use-package-ensure-system-package try treemacs-projectile treemacs-magit treemacs-icons-dired treemacs-evil toml-mode tide telephone-line sublimity solaire-mode smooth-scrolling smartscan smart-mode-line-powerline-theme shell-pop selectric-mode scss-mode scrollkeeper rust-mode ruby-tools ruby-refactor ruby-hash-syntax ruby-extra-highlight ruby-compilation ruby-additional rubocop rspec-mode rotate rjsx-mode right-click-context rg request ranger rainbow-mode rainbow-delimiters quickrun quick-peek projectile-rails prettier-js pdf-tools parsebib parrot parinfer pacmacs ox-reveal ox-gfm outshine org-sidebar org-plus-contrib org-kanban org-bullets ob-restclient nyan-mode noccur neotree nav-flash mu4e-alert move-text minions mini-modeline major-mode-hydra magit-todos magit-stgit magit-popup lsp-ui lsp-treemacs lsp-ivy latex-preview-pane keyfreq key-chord json-mode js-import ivy-rich ivy-prescient ivy-posframe ivy-explorer indium iedit ialign htmlize hl-anything highlight-thing highlight-parentheses highlight-operators highlight-numbers highlight-indent-guides highlight-escape-sequences highlight-context-line hide-mode-line helpful guess-language gruvbox-theme gradle-mode goto-line-preview go gitignore-mode gitconfig-mode gitattributes-mode git-timemachine git-messenger format-all forge flycheck-posframe flycheck-pos-tip flycheck-popup-tip flycheck-inline flycheck-haskell flycheck-gometalinter flx fireplace feebleline fast-scroll fancy-battery eyebrowse expand-region exec-path-from-shell evil-visualstar evil-surround evil-smartparens evil-paredit evil-org evil-numbers evil-mu4e evil-mc evil-matchit evil-magit evil-lion evil-leader evil-goggles evil-escape evil-easymotion evil-commentary eslintd-fix enh-ruby-mode emojify elm-mode elisp-format eldoc-box editorconfig dumb-jump dracula-theme dotenv-mode doom-themes doom-modeline dockerfile-mode docker-compose-mode discover dired-sidebar dired-k dimmer diminish diffview diff-hl dashboard darktooth-theme dap-mode crux counsel-projectile corral company-restclient company-quickhelp company-prescient company-posframe company-lsp company-go company-emoji company-box company-auctex color-identifiers-mode cheat-sh centered-cursor-mode centaur-tabs celestial-mode-line c-c-combo bundler bug-hunter biblio beacon base16-theme auto-package-update atom-one-dark-theme anzu amx all-the-icons-ivy all-the-icons-dired alchemist aggressive-indent ag add-node-modules-path ace-jump-mode ac-php-core ac-emmet)))
 '(projectile-completion-system (quote ivy) t)
 '(swiper-action-recenter t)
 '(treemacs-deferred-git-apply-delay 0.5)
 '(treemacs-display-in-side-window t)
 '(treemacs-eldoc-display t)
 '(treemacs-file-event-delay 5000)
 '(treemacs-file-follow-delay 0.2)
 '(treemacs-follow-after-init t)
 '(treemacs-git-command-pipe "")
 '(treemacs-goto-tag-strategy (quote refetch-index))
 '(treemacs-indentation 2)
 '(treemacs-indentation-string " ")
 '(treemacs-is-never-other-window nil)
 '(treemacs-max-git-entries 5000)
 '(treemacs-missing-project-action (quote ask))
 '(treemacs-no-delete-other-windows t)
 '(treemacs-no-png-images nil)
 '(treemacs-persist-file "/home/tau/.emacs.d/.cache/treemacs-persist")
 '(treemacs-position (quote left))
 '(treemacs-project-follow-cleanup nil)
 '(treemacs-recenter-after-file-follow nil)
 '(treemacs-recenter-after-project-expand (quote on-distance))
 '(treemacs-recenter-after-project-jump (quote always))
 '(treemacs-recenter-after-tag-follow nil)
 '(treemacs-recenter-distance 0.1)
 '(treemacs-show-cursor nil)
 '(treemacs-show-hidden-files t)
 '(treemacs-silent-filewatch nil)
 '(treemacs-silent-refresh nil)
 '(treemacs-sorting (quote alphabetic-desc))
 '(treemacs-space-between-root-nodes t)
 '(treemacs-tag-follow-cleanup t)
 '(treemacs-tag-follow-delay 1.5)
 '(treemacs-width 35)
 '(wgrep-auto-save-buffer t t)
 '(wgrep-change-readonly-file t t)
 '(wgrep-enable-key "e" t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(anzu-mode-line ((nil (:foreground "yellow" :weight (quote bold)))))
 '(aw-leading-char-face ((t (:height 4.0 :foreground "#f1fa8c"))))
 '(company-preview-common ((t (:foreground unspecified :background "#111111"))))
 '(company-scrollbar-bg ((t (:background "#111111"))))
 '(company-scrollbar-fg ((t (:background "#555555"))))
 '(company-tooltip ((t (:inherit default :background "#202029"))))
 '(company-tooltip-common ((t (:inherit font-lock-constant-face))))
 '(company-tooltip-selection ((t (:inherit company-tooltip-common :background "#2a2a2a"))))
 '(css-selector ((t (:inherit default :foreground "#66CCFF"))))
 '(dashboard-banner-logo-title ((t (:family "Love LetterTW" :height 123))))
 '(dashboard-heading ((t (:foreground "#f1fa8c" :weight bold))))
 '(diff-hl-change ((t (:foreground "#f4f4f4"))))
 '(diff-hl-delete ((t (:background "#ee6363"))))
 '(diff-hl-insert ((t (:background "#7ccd7c"))))
 '(flycheck-posframe-background-face ((nil (:background "#FFFFFF" :foreground "#000000"))))
 '(flycheck-posframe-border-face ((nil (:background "#af3ec8"))))
 '(flycheck-posframe-error-face ((nil (:inherit (quote error)))))
 '(flycheck-posframe-face ((nil (:background "#20fabe" :foreground "#FFCC0E"))))
 '(flycheck-posframe-info-face ((nil (:inherit (quote info)))))
 '(flycheck-posframe-warning-face ((nil (:background "#fcfa23" :foreground "#000000"))))
 '(font-lock-comment-face ((t (:foreground "#828282"))))
 '(hydra-posframe-border-face ((t (:background "#6272a4"))))
 '(ivy-posframe ((t (:background "#333244"))))
 '(ivy-posframe-border ((t (:background "#abff00"))))
 '(ivy-posframe-cursor ((t (:background "#00ff00"))))
 '(lsp-ui-doc-background ((nil (:background "#f9f2d9"))))
 '(lsp-ui-doc-header ((t (:inherit (font-lock-string-face italic)))))
 '(lsp-ui-sideline-global ((nil (:inherit (quote shadow) :background "#f9f2d9"))))
 '(show-paren-match ((nil (:background "#44475a" :foreground "#f1fa8c"))))
 '(show-paren-mismatch ((nil (:background "red" :foreground "black")))))
